import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "../widgets/header/header";
import { SidebarProvider } from "@/shared/components/ui/sidebar";
import { AppSidebar } from "../widgets/sidebar/app-sidebar";
import { TooltipProvider } from "@/shared/components/ui/tooltip";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin", "latin-ext"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SidebarProvider>
          <TooltipProvider>
            <AppSidebar />
            <Header />
            <main>{children}</main>
          </TooltipProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
