import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import AppLayout from "./providers";
import { AppSidebar } from "@/widgets/sidebar";
import { SidebarTrigger } from "@/shared/components/ui/sidebar";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin", "latin-ext"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-svh bg-background antialiased">
        <AppLayout>
          <AppSidebar />
          <div className="flex flex-1 flex-col gap-2 p-2">
            <SidebarTrigger className="md:hidden sticky top-2 z-50 self-start" />
            <div className="flex-1 p-4">{children}</div>
          </div>
        </AppLayout>
      </body>
    </html>
  );
}
