<Project Sdk="Microsoft.NET.Sdk">
  
	<ItemGroup>
		<PackageReference Include="CSharpFunctionalExtensions" />
	</ItemGroup>

  <PropertyGroup>
    <PackageId>DirectoryService.SharedKernel</PackageId>
    <Version>1.0.2</Version>
    <Authors>lokixx15</Authors>
    <Company>lokixx15</Company>
    <PackageDescription>SharedKernel</PackageDescription>
    <RepositoryUrl>https://github.com/lokixx15/DirectoryService</RepositoryUrl>
  </PropertyGroup>
  
</Project>
