<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.3.26" />
    <PackageVersion Include="AWSSDK.S3" Version="4.0.19.1" />
    <PackageVersion Include="CrystalQuartz.AspNetCore" Version="7.3.0" />
    <PackageVersion Include="CSharpFunctionalExtensions" Version="3.7.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.14" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.14" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.14" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="9.0.14" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.14" />
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageVersion Include="Quartz" Version="3.18.1" />
    <PackageVersion Include="Quartz.Extensions.Hosting" Version="3.18.1" />
    <PackageVersion Include="Quartz.Serialization.Json" Version="3.18.1" />
    <PackageVersion Include="Respawn" Version="7.0.0" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.1.118" />
    <PackageVersion Include="DirectoryService.Core" Version="1.0.2" />
    <PackageVersion Include="DirectoryService.SharedKernel" Version="1.0.3" />
    <PackageVersion Include="DirectoryService.Framework" Version="1.0.2" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
    <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="Testcontainers.Minio" Version="4.11.0" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.11.0" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>