<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.14" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.1.118" />
    <PackageVersion Include="DirectoryService.Core" Version="1.0.1" />
    <PackageVersion Include="DirectoryService.SharedKernel" Version="1.0.0" />
    <PackageVersion Include="DirectoryService.Framework" Version="1.0.1" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
    <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.0" />
  </ItemGroup>
</Project>