services:
  directory-service:
    container_name: directory-service
    build: 
      context: ./DirectoryService
      dockerfile: Dockerfile
      args:
        NUGET_USERNAME: ${NUGET_USERNAME}
        NUGET_PASSWORD: ${NUGET_PASSWORD}
    env_file:
      - .env
    ports:
    - "9001:9001"
    environment:
    - ASPNETCORE_ENVIRONMENT=Docker
    - ASPNETCORE_URLS=http://+:9001
    depends_on:
      - postgres
    restart: always

  file-service:
    container_name: file-service
    build: 
      context: ./FileService
      dockerfile: Dockerfile
      args:
        NUGET_USERNAME: ${NUGET_USERNAME}
        NUGET_PASSWORD: ${NUGET_PASSWORD}
    env_file:
      - .env
    ports:
    - "9002:9002"
    environment:
    - ASPNETCORE_ENVIRONMENT=Docker
    - ASPNETCORE_URLS=http://+:9002
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: directory_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "8081:80"
      - "5341:5341"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    restart: always

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes: 
      - redis_data:/data
    restart: always

volumes:
  postgres-data:
  redis_data: